import type { Metadata } from "next";
import "./globals.css";
import { noto } from "@/app/ui/fonts";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { SocketProvider } from "@/context/SocketContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body
          className={`${noto.className}
              min-h-screen bg-background font-sans antialiased`}
        >
          <SocketProvider>{children}</SocketProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
