# clones repo, installs dependencies and runs typescript compiler on pull request

name: Node.js setup

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm i
      - run: npm run tsc
      - run: echo "PR is ready to be reviewed!"
